version: '2.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    volumes:
      - ./src:/app
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_USER: your_db_user
      POSTGRES_DB: your_db_name


volumes:
  postgres_data:
